default_job = "check"

[jobs.check]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true

[jobs.nextest]
command = ["cargo", "nextest", "run", "--all-targets", "--color", "always"]
need_stdout = true

[jobs.test]
command = ["cargo", "test", "--all-targets", "--color", "always"]
need_stdout = true

[jobs.coverage]
command = [
  "cargo",
  "tarpaulin",
  "--all-targets",
  "--ignore-tests",
  "--out",
  "Html",
]
need_stdout = true

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
  "--",
  "-D",
  "warnings",
]
need_stdout = false

[jobs.fmt]
command = ["cargo", "fmt", "--all"]
need_stdout = true
on_success = "back"

[jobs.fmt-check]
command = ["cargo", "fmt", "--all", "--check"]
need_stdout = true

[keybindings]
r = "job:run"
t = "job:nextest"
c = "job:clippy"
f = "job:fmt"
x = "job:fmt-check"
v = "job:coverage"
